- name: Configure web servers
  hosts: all
  become: true

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: latest
        update_cache: true

    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        mode: '0755'

    - name: unlink default nginx conf
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/nginx.conf

    - name: create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        state: link

    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /web/html/index.html
        owner: www-data
        group: www-data
        mode: '0655'

    - name: reload nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
